[features]
seeds = false
skip-lint = false

[programs.localnet]
my_solami_token = "EQ85HBoFJ6FiLz5NLZSuLnJ2Wr71q3P27rggw1z2WYAY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/apple/solana/solami-keypair.json"

[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.2"

